logging:
  pattern:
    console: "[Practical Java Spring Boot ELK] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "[Practical ELK] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/practical-elk.log
    
    
spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE
    
management:
  metrics:
    export:
      elastic:
        step: 30s
        host: http://localhost:9200